/* 
  Migration for Air Sensor customizable thresholds
  Adds warning and critical min/max threshold values to air_sensors table
*/
ALTER TABLE public.air_sensors
ADD COLUMN IF NOT EXISTS temp_min_warning NUMERIC DEFAULT 18.0,
ADD COLUMN IF NOT EXISTS temp_max_warning NUMERIC DEFAULT 26.0,
ADD COLUMN IF NOT EXISTS temp_min_critical NUMERIC DEFAULT 15.0,
ADD COLUMN IF NOT EXISTS temp_max_critical NUMERIC DEFAULT 32.0,

ADD COLUMN IF NOT EXISTS hum_min_warning NUMERIC DEFAULT 30.0,
ADD COLUMN IF NOT EXISTS hum_max_warning NUMERIC DEFAULT 60.0,
ADD COLUMN IF NOT EXISTS hum_min_critical NUMERIC DEFAULT 20.0,
ADD COLUMN IF NOT EXISTS hum_max_critical NUMERIC DEFAULT 80.0,

ADD COLUMN IF NOT EXISTS pm25_warning NUMERIC DEFAULT 35.0,
ADD COLUMN IF NOT EXISTS pm25_critical NUMERIC DEFAULT 75.0,

ADD COLUMN IF NOT EXISTS tvoc_warning NUMERIC DEFAULT 500.0,
ADD COLUMN IF NOT EXISTS tvoc_critical NUMERIC DEFAULT 1500.0,

ADD COLUMN IF NOT EXISTS co2_warning NUMERIC DEFAULT 1000.0,
ADD COLUMN IF NOT EXISTS co2_critical NUMERIC DEFAULT 2000.0;
